name: Bug Report ðŸž
description: File a bug report
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        > [!note]
        > - Use `Discussions` if you want to ask for questions

  - type: input
    id: device_info
    attributes:
      label: "Device model and version"
      placeholder: "e.g., Clara BW, 4.44.23552"
    validations:
      required: true

  - type: input
    id: addon_version
    attributes:
      label: "Kobo Tweaks version"
      placeholder: "You can get this info in .adds/tweaks/DELETE_TO_UNINSTALL.txt"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Describe the bug"
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: "Screenshot/video"
      description: |
        Please provide screenshot/video of the bug if possible.
    validations:
      required: false
